theme: jekyll-theme-cayman
title:  Data Science Project Portfolio
description: My framework outperforms the <a href="https://github.com/drossDS" style="color: red">current industry standard</a> as can be seen in publicly available <a href="https://github.com/drossDS">benchmarks</a>.
