theme: jekyll-theme-cayman
title:  Data Science Project Portfolio
description: Daniel David Rossetti | <a href="https://github.com/drossDS" style="color: red">current industry standard</a> | 978-417-1001
